### ISSUE TITLE
retrofit请求方式

### ISSUE THREAD

**Issue by jingkais** [BTPJ/WanAndroid#4]
大佬请问 您项目中的retrofit请求方式是异步还是同步，看起来像是同步的 对吗

**Comment by Toping123** [comment]
异步请求的，只是kotlin的协程让异步看起来像同步啊

**Comment by jingkais** [comment]
请问具体表现的代码是哪里呢 比如execute  enqueue 的调用方式呢

**Comment by jingkais** [comment]
我看了一下BaseViewModel.handleRequest中的返回的实际是泛型<T>所以推断是同步请求。
